// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aws-pricing.proto

/*
Package bo is a generated protocol buffer package.

It is generated from these files:
	aws-pricing.proto

It has these top-level messages:
	ItemID
	LineItem
*/
package bo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ItemID struct {
	IdentityLineItemID string `protobuf:"bytes,1,opt,name=IdentityLineItemID" json:"IdentityLineItemID,omitempty"`
}

func (m *ItemID) Reset()                    { *m = ItemID{} }
func (m *ItemID) String() string            { return proto.CompactTextString(m) }
func (*ItemID) ProtoMessage()               {}
func (*ItemID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ItemID) GetIdentityLineItemID() string {
	if m != nil {
		return m.IdentityLineItemID
	}
	return ""
}

type LineItem struct {
	IdentityLineItemID            string `protobuf:"bytes,1,opt,name=IdentityLineItemID" json:"IdentityLineItemID,omitempty"`
	IdentityTimeInterval          string `protobuf:"bytes,2,opt,name=IdentityTimeInterval" json:"IdentityTimeInterval,omitempty"`
	BillInvoiceID                 string `protobuf:"bytes,3,opt,name=BillInvoiceID" json:"BillInvoiceID,omitempty"`
	BillBillingEntity             string `protobuf:"bytes,4,opt,name=BillBillingEntity" json:"BillBillingEntity,omitempty"`
	BillBillType                  string `protobuf:"bytes,5,opt,name=BillBillType" json:"BillBillType,omitempty"`
	BillPayerAccountID            string `protobuf:"bytes,6,opt,name=BillPayerAccountID" json:"BillPayerAccountID,omitempty"`
	BillBillingPeriodStartDate    string `protobuf:"bytes,7,opt,name=BillBillingPeriodStartDate" json:"BillBillingPeriodStartDate,omitempty"`
	BillBillingPeriodEndDate      string `protobuf:"bytes,8,opt,name=BillBillingPeriodEndDate" json:"BillBillingPeriodEndDate,omitempty"`
	LineItemUsageAccountID        string `protobuf:"bytes,9,opt,name=LineItemUsageAccountID" json:"LineItemUsageAccountID,omitempty"`
	LineItemLineItemType          string `protobuf:"bytes,10,opt,name=LineItemLineItemType" json:"LineItemLineItemType,omitempty"`
	LineItemUsageStartDate        string `protobuf:"bytes,11,opt,name=LineItemUsageStartDate" json:"LineItemUsageStartDate,omitempty"`
	LineItemUsageEndDate          string `protobuf:"bytes,12,opt,name=LineItemUsageEndDate" json:"LineItemUsageEndDate,omitempty"`
	LineItemProductCode           string `protobuf:"bytes,13,opt,name=LineItemProductCode" json:"LineItemProductCode,omitempty"`
	LineItemUsageType             string `protobuf:"bytes,14,opt,name=LineItemUsageType" json:"LineItemUsageType,omitempty"`
	LineItemOperation             string `protobuf:"bytes,15,opt,name=LineItemOperation" json:"LineItemOperation,omitempty"`
	LineItemAvailabilityZone      string `protobuf:"bytes,16,opt,name=LineItemAvailabilityZone" json:"LineItemAvailabilityZone,omitempty"`
	LineItemResourceID            string `protobuf:"bytes,17,opt,name=LineItemResourceID" json:"LineItemResourceID,omitempty"`
	LineItemUsageAmount           string `protobuf:"bytes,18,opt,name=LineItemUsageAmount" json:"LineItemUsageAmount,omitempty"`
	LineItemNormalizationFactor   string `protobuf:"bytes,19,opt,name=LineItemNormalizationFactor" json:"LineItemNormalizationFactor,omitempty"`
	LineItemNormalizedUsageAmount string `protobuf:"bytes,20,opt,name=LineItemNormalizedUsageAmount" json:"LineItemNormalizedUsageAmount,omitempty"`
	LineItemCurrencyCode          string `protobuf:"bytes,21,opt,name=LineItemCurrencyCode" json:"LineItemCurrencyCode,omitempty"`
	LineItemUnblendedRate         string `protobuf:"bytes,22,opt,name=LineItemUnblendedRate" json:"LineItemUnblendedRate,omitempty"`
	LineItemUnblendedCost         string `protobuf:"bytes,23,opt,name=LineItemUnblendedCost" json:"LineItemUnblendedCost,omitempty"`
	LineItemBlendedRate           string `protobuf:"bytes,24,opt,name=LineItemBlendedRate" json:"LineItemBlendedRate,omitempty"`
	LineItemBlendedCost           string `protobuf:"bytes,25,opt,name=LineItemBlendedCost" json:"LineItemBlendedCost,omitempty"`
	LineItemLineItemDescription   string `protobuf:"bytes,26,opt,name=LineItemLineItemDescription" json:"LineItemLineItemDescription,omitempty"`
	LineItemTaxType               string `protobuf:"bytes,27,opt,name=LineItemTaxType" json:"LineItemTaxType,omitempty"`
	NormalizedUnitsPerReservation string `protobuf:"bytes,28,opt,name=NormalizedUnitsPerReservation" json:"NormalizedUnitsPerReservation,omitempty"`
	TotalReservedNormalizedUnits  string `protobuf:"bytes,29,opt,name=TotalReservedNormalizedUnits" json:"TotalReservedNormalizedUnits,omitempty"`
	TotalReservedUnits            string `protobuf:"bytes,30,opt,name=TotalReservedUnits" json:"TotalReservedUnits,omitempty"`
	UnitsPerReservation           string `protobuf:"bytes,31,opt,name=UnitsPerReservation" json:"UnitsPerReservation,omitempty"`
	PublicOnDemandCost            string `protobuf:"bytes,32,opt,name=PublicOnDemandCost" json:"PublicOnDemandCost,omitempty"`
	PublicOnDemandRate            string `protobuf:"bytes,33,opt,name=PublicOnDemandRate" json:"PublicOnDemandRate,omitempty"`
	Term                          string `protobuf:"bytes,34,opt,name=Term" json:"Term,omitempty"`
	Unit                          string `protobuf:"bytes,35,opt,name=Unit" json:"Unit,omitempty"`
	ProductName                   string `protobuf:"bytes,36,opt,name=ProductName" json:"ProductName,omitempty"`
	Availability                  string `protobuf:"bytes,37,opt,name=Availability" json:"Availability,omitempty"`
	ClockSpeed                    string `protobuf:"bytes,38,opt,name=ClockSpeed" json:"ClockSpeed,omitempty"`
	CurrentGeneration             string `protobuf:"bytes,39,opt,name=CurrentGeneration" json:"CurrentGeneration,omitempty"`
	Durability                    string `protobuf:"bytes,40,opt,name=Durability" json:"Durability,omitempty"`
	Ecu                           string `protobuf:"bytes,41,opt,name=Ecu" json:"Ecu,omitempty"`
	FromLocation                  string `protobuf:"bytes,42,opt,name=FromLocation" json:"FromLocation,omitempty"`
	FromLocationType              string `protobuf:"bytes,43,opt,name=FromLocationType" json:"FromLocationType,omitempty"`
	Group                         string `protobuf:"bytes,44,opt,name=Group" json:"Group,omitempty"`
	GroupDescription              string `protobuf:"bytes,45,opt,name=GroupDescription" json:"GroupDescription,omitempty"`
	InstanceFamily                string `protobuf:"bytes,46,opt,name=InstanceFamily" json:"InstanceFamily,omitempty"`
	InstanceType                  string `protobuf:"bytes,47,opt,name=InstanceType" json:"InstanceType,omitempty"`
	InstanceTypeFamily            string `protobuf:"bytes,48,opt,name=InstanceTypeFamily" json:"InstanceTypeFamily,omitempty"`
	LicenseModel                  string `protobuf:"bytes,49,opt,name=LicenseModel" json:"LicenseModel,omitempty"`
	Location                      string `protobuf:"bytes,50,opt,name=Location" json:"Location,omitempty"`
	LocationType                  string `protobuf:"bytes,51,opt,name=LocationType" json:"LocationType,omitempty"`
	MaxIopsBurstPerformance       string `protobuf:"bytes,52,opt,name=MaxIopsBurstPerformance" json:"MaxIopsBurstPerformance,omitempty"`
	MaxIopsvolume                 string `protobuf:"bytes,53,opt,name=MaxIopsvolume" json:"MaxIopsvolume,omitempty"`
	MaxThroughputvolume           string `protobuf:"bytes,54,opt,name=MaxThroughputvolume" json:"MaxThroughputvolume,omitempty"`
	MaxVolumeSize                 string `protobuf:"bytes,55,opt,name=MaxVolumeSize" json:"MaxVolumeSize,omitempty"`
	Memory                        string `protobuf:"bytes,56,opt,name=Memory" json:"Memory,omitempty"`
	NetworkPerformance            string `protobuf:"bytes,57,opt,name=NetworkPerformance" json:"NetworkPerformance,omitempty"`
	NormalizationSizeFactor       string `protobuf:"bytes,58,opt,name=NormalizationSizeFactor" json:"NormalizationSizeFactor,omitempty"`
	OperatingSystem               string `protobuf:"bytes,59,opt,name=OperatingSystem" json:"OperatingSystem,omitempty"`
	Operation                     string `protobuf:"bytes,60,opt,name=Operation" json:"Operation,omitempty"`
	PhysicalProcessor             string `protobuf:"bytes,61,opt,name=PhysicalProcessor" json:"PhysicalProcessor,omitempty"`
	PreInstalledSw                string `protobuf:"bytes,62,opt,name=PreInstalledSw" json:"PreInstalledSw,omitempty"`
	ProcessorArchitecture         string `protobuf:"bytes,63,opt,name=ProcessorArchitecture" json:"ProcessorArchitecture,omitempty"`
	ProcessorFeatures             string `protobuf:"bytes,64,opt,name=ProcessorFeatures" json:"ProcessorFeatures,omitempty"`
	ProductFamily                 string `protobuf:"bytes,65,opt,name=ProductFamily" json:"ProductFamily,omitempty"`
	Provisioned                   string `protobuf:"bytes,66,opt,name=Provisioned" json:"Provisioned,omitempty"`
	Region                        string `protobuf:"bytes,67,opt,name=Region" json:"Region,omitempty"`
	Servicecode                   string `protobuf:"bytes,68,opt,name=Servicecode" json:"Servicecode,omitempty"`
	Servicename                   string `protobuf:"bytes,69,opt,name=Servicename" json:"Servicename,omitempty"`
	Sku                           string `protobuf:"bytes,70,opt,name=Sku" json:"Sku,omitempty"`
	Storage                       string `protobuf:"bytes,71,opt,name=Storage" json:"Storage,omitempty"`
	StorageClass                  string `protobuf:"bytes,72,opt,name=StorageClass" json:"StorageClass,omitempty"`
	StorageMedia                  string `protobuf:"bytes,73,opt,name=StorageMedia" json:"StorageMedia,omitempty"`
	Tenancy                       string `protobuf:"bytes,74,opt,name=Tenancy" json:"Tenancy,omitempty"`
	ToLocation                    string `protobuf:"bytes,75,opt,name=ToLocation" json:"ToLocation,omitempty"`
	ToLocationType                string `protobuf:"bytes,76,opt,name=ToLocationType" json:"ToLocationType,omitempty"`
	TransferType                  string `protobuf:"bytes,77,opt,name=TransferType" json:"TransferType,omitempty"`
	Usagetype                     string `protobuf:"bytes,78,opt,name=Usagetype" json:"Usagetype,omitempty"`
	Vcpu                          string `protobuf:"bytes,79,opt,name=Vcpu" json:"Vcpu,omitempty"`
	VolumeType                    string `protobuf:"bytes,80,opt,name=VolumeType" json:"VolumeType,omitempty"`
}

func (m *LineItem) Reset()                    { *m = LineItem{} }
func (m *LineItem) String() string            { return proto.CompactTextString(m) }
func (*LineItem) ProtoMessage()               {}
func (*LineItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LineItem) GetIdentityLineItemID() string {
	if m != nil {
		return m.IdentityLineItemID
	}
	return ""
}

func (m *LineItem) GetIdentityTimeInterval() string {
	if m != nil {
		return m.IdentityTimeInterval
	}
	return ""
}

func (m *LineItem) GetBillInvoiceID() string {
	if m != nil {
		return m.BillInvoiceID
	}
	return ""
}

func (m *LineItem) GetBillBillingEntity() string {
	if m != nil {
		return m.BillBillingEntity
	}
	return ""
}

func (m *LineItem) GetBillBillType() string {
	if m != nil {
		return m.BillBillType
	}
	return ""
}

func (m *LineItem) GetBillPayerAccountID() string {
	if m != nil {
		return m.BillPayerAccountID
	}
	return ""
}

func (m *LineItem) GetBillBillingPeriodStartDate() string {
	if m != nil {
		return m.BillBillingPeriodStartDate
	}
	return ""
}

func (m *LineItem) GetBillBillingPeriodEndDate() string {
	if m != nil {
		return m.BillBillingPeriodEndDate
	}
	return ""
}

func (m *LineItem) GetLineItemUsageAccountID() string {
	if m != nil {
		return m.LineItemUsageAccountID
	}
	return ""
}

func (m *LineItem) GetLineItemLineItemType() string {
	if m != nil {
		return m.LineItemLineItemType
	}
	return ""
}

func (m *LineItem) GetLineItemUsageStartDate() string {
	if m != nil {
		return m.LineItemUsageStartDate
	}
	return ""
}

func (m *LineItem) GetLineItemUsageEndDate() string {
	if m != nil {
		return m.LineItemUsageEndDate
	}
	return ""
}

func (m *LineItem) GetLineItemProductCode() string {
	if m != nil {
		return m.LineItemProductCode
	}
	return ""
}

func (m *LineItem) GetLineItemUsageType() string {
	if m != nil {
		return m.LineItemUsageType
	}
	return ""
}

func (m *LineItem) GetLineItemOperation() string {
	if m != nil {
		return m.LineItemOperation
	}
	return ""
}

func (m *LineItem) GetLineItemAvailabilityZone() string {
	if m != nil {
		return m.LineItemAvailabilityZone
	}
	return ""
}

func (m *LineItem) GetLineItemResourceID() string {
	if m != nil {
		return m.LineItemResourceID
	}
	return ""
}

func (m *LineItem) GetLineItemUsageAmount() string {
	if m != nil {
		return m.LineItemUsageAmount
	}
	return ""
}

func (m *LineItem) GetLineItemNormalizationFactor() string {
	if m != nil {
		return m.LineItemNormalizationFactor
	}
	return ""
}

func (m *LineItem) GetLineItemNormalizedUsageAmount() string {
	if m != nil {
		return m.LineItemNormalizedUsageAmount
	}
	return ""
}

func (m *LineItem) GetLineItemCurrencyCode() string {
	if m != nil {
		return m.LineItemCurrencyCode
	}
	return ""
}

func (m *LineItem) GetLineItemUnblendedRate() string {
	if m != nil {
		return m.LineItemUnblendedRate
	}
	return ""
}

func (m *LineItem) GetLineItemUnblendedCost() string {
	if m != nil {
		return m.LineItemUnblendedCost
	}
	return ""
}

func (m *LineItem) GetLineItemBlendedRate() string {
	if m != nil {
		return m.LineItemBlendedRate
	}
	return ""
}

func (m *LineItem) GetLineItemBlendedCost() string {
	if m != nil {
		return m.LineItemBlendedCost
	}
	return ""
}

func (m *LineItem) GetLineItemLineItemDescription() string {
	if m != nil {
		return m.LineItemLineItemDescription
	}
	return ""
}

func (m *LineItem) GetLineItemTaxType() string {
	if m != nil {
		return m.LineItemTaxType
	}
	return ""
}

func (m *LineItem) GetNormalizedUnitsPerReservation() string {
	if m != nil {
		return m.NormalizedUnitsPerReservation
	}
	return ""
}

func (m *LineItem) GetTotalReservedNormalizedUnits() string {
	if m != nil {
		return m.TotalReservedNormalizedUnits
	}
	return ""
}

func (m *LineItem) GetTotalReservedUnits() string {
	if m != nil {
		return m.TotalReservedUnits
	}
	return ""
}

func (m *LineItem) GetUnitsPerReservation() string {
	if m != nil {
		return m.UnitsPerReservation
	}
	return ""
}

func (m *LineItem) GetPublicOnDemandCost() string {
	if m != nil {
		return m.PublicOnDemandCost
	}
	return ""
}

func (m *LineItem) GetPublicOnDemandRate() string {
	if m != nil {
		return m.PublicOnDemandRate
	}
	return ""
}

func (m *LineItem) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

func (m *LineItem) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *LineItem) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *LineItem) GetAvailability() string {
	if m != nil {
		return m.Availability
	}
	return ""
}

func (m *LineItem) GetClockSpeed() string {
	if m != nil {
		return m.ClockSpeed
	}
	return ""
}

func (m *LineItem) GetCurrentGeneration() string {
	if m != nil {
		return m.CurrentGeneration
	}
	return ""
}

func (m *LineItem) GetDurability() string {
	if m != nil {
		return m.Durability
	}
	return ""
}

func (m *LineItem) GetEcu() string {
	if m != nil {
		return m.Ecu
	}
	return ""
}

func (m *LineItem) GetFromLocation() string {
	if m != nil {
		return m.FromLocation
	}
	return ""
}

func (m *LineItem) GetFromLocationType() string {
	if m != nil {
		return m.FromLocationType
	}
	return ""
}

func (m *LineItem) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *LineItem) GetGroupDescription() string {
	if m != nil {
		return m.GroupDescription
	}
	return ""
}

func (m *LineItem) GetInstanceFamily() string {
	if m != nil {
		return m.InstanceFamily
	}
	return ""
}

func (m *LineItem) GetInstanceType() string {
	if m != nil {
		return m.InstanceType
	}
	return ""
}

func (m *LineItem) GetInstanceTypeFamily() string {
	if m != nil {
		return m.InstanceTypeFamily
	}
	return ""
}

func (m *LineItem) GetLicenseModel() string {
	if m != nil {
		return m.LicenseModel
	}
	return ""
}

func (m *LineItem) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *LineItem) GetLocationType() string {
	if m != nil {
		return m.LocationType
	}
	return ""
}

func (m *LineItem) GetMaxIopsBurstPerformance() string {
	if m != nil {
		return m.MaxIopsBurstPerformance
	}
	return ""
}

func (m *LineItem) GetMaxIopsvolume() string {
	if m != nil {
		return m.MaxIopsvolume
	}
	return ""
}

func (m *LineItem) GetMaxThroughputvolume() string {
	if m != nil {
		return m.MaxThroughputvolume
	}
	return ""
}

func (m *LineItem) GetMaxVolumeSize() string {
	if m != nil {
		return m.MaxVolumeSize
	}
	return ""
}

func (m *LineItem) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *LineItem) GetNetworkPerformance() string {
	if m != nil {
		return m.NetworkPerformance
	}
	return ""
}

func (m *LineItem) GetNormalizationSizeFactor() string {
	if m != nil {
		return m.NormalizationSizeFactor
	}
	return ""
}

func (m *LineItem) GetOperatingSystem() string {
	if m != nil {
		return m.OperatingSystem
	}
	return ""
}

func (m *LineItem) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *LineItem) GetPhysicalProcessor() string {
	if m != nil {
		return m.PhysicalProcessor
	}
	return ""
}

func (m *LineItem) GetPreInstalledSw() string {
	if m != nil {
		return m.PreInstalledSw
	}
	return ""
}

func (m *LineItem) GetProcessorArchitecture() string {
	if m != nil {
		return m.ProcessorArchitecture
	}
	return ""
}

func (m *LineItem) GetProcessorFeatures() string {
	if m != nil {
		return m.ProcessorFeatures
	}
	return ""
}

func (m *LineItem) GetProductFamily() string {
	if m != nil {
		return m.ProductFamily
	}
	return ""
}

func (m *LineItem) GetProvisioned() string {
	if m != nil {
		return m.Provisioned
	}
	return ""
}

func (m *LineItem) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *LineItem) GetServicecode() string {
	if m != nil {
		return m.Servicecode
	}
	return ""
}

func (m *LineItem) GetServicename() string {
	if m != nil {
		return m.Servicename
	}
	return ""
}

func (m *LineItem) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *LineItem) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *LineItem) GetStorageClass() string {
	if m != nil {
		return m.StorageClass
	}
	return ""
}

func (m *LineItem) GetStorageMedia() string {
	if m != nil {
		return m.StorageMedia
	}
	return ""
}

func (m *LineItem) GetTenancy() string {
	if m != nil {
		return m.Tenancy
	}
	return ""
}

func (m *LineItem) GetToLocation() string {
	if m != nil {
		return m.ToLocation
	}
	return ""
}

func (m *LineItem) GetToLocationType() string {
	if m != nil {
		return m.ToLocationType
	}
	return ""
}

func (m *LineItem) GetTransferType() string {
	if m != nil {
		return m.TransferType
	}
	return ""
}

func (m *LineItem) GetUsagetype() string {
	if m != nil {
		return m.Usagetype
	}
	return ""
}

func (m *LineItem) GetVcpu() string {
	if m != nil {
		return m.Vcpu
	}
	return ""
}

func (m *LineItem) GetVolumeType() string {
	if m != nil {
		return m.VolumeType
	}
	return ""
}

func init() {
	proto.RegisterType((*ItemID)(nil), "bo.ItemID")
	proto.RegisterType((*LineItem)(nil), "bo.LineItem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Pricing service

type PricingClient interface {
	ListItem(ctx context.Context, in *ItemID, opts ...grpc.CallOption) (*LineItem, error)
}

type pricingClient struct {
	cc *grpc.ClientConn
}

func NewPricingClient(cc *grpc.ClientConn) PricingClient {
	return &pricingClient{cc}
}

func (c *pricingClient) ListItem(ctx context.Context, in *ItemID, opts ...grpc.CallOption) (*LineItem, error) {
	out := new(LineItem)
	err := grpc.Invoke(ctx, "/bo.Pricing/ListItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pricing service

type PricingServer interface {
	ListItem(context.Context, *ItemID) (*LineItem, error)
}

func RegisterPricingServer(s *grpc.Server, srv PricingServer) {
	s.RegisterService(&_Pricing_serviceDesc, srv)
}

func _Pricing_ListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServer).ListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bo.Pricing/ListItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServer).ListItem(ctx, req.(*ItemID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pricing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bo.Pricing",
	HandlerType: (*PricingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListItem",
			Handler:    _Pricing_ListItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aws-pricing.proto",
}

func init() { proto.RegisterFile("aws-pricing.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xeb, 0x73, 0x13, 0x37,
	0x10, 0x1f, 0x5e, 0x01, 0xc4, 0x5b, 0xbc, 0xd4, 0xf0, 0x28, 0x4d, 0x29, 0xa5, 0x14, 0x02, 0x05,
	0x4a, 0x29, 0x6d, 0x29, 0x49, 0x9c, 0x50, 0xb7, 0x49, 0xf0, 0xc4, 0x2e, 0x1f, 0xfa, 0x4d, 0xb9,
	0x5b, 0x12, 0x4d, 0xce, 0x92, 0x47, 0xa7, 0x0b, 0x98, 0x3f, 0xb8, 0x7f, 0x47, 0x67, 0x77, 0xef,
	0x6c, 0x9d, 0xef, 0x92, 0x99, 0x7e, 0xf0, 0x58, 0xfa, 0xfd, 0xf6, 0x25, 0xed, 0x6a, 0xa5, 0x13,
	0x97, 0xf4, 0xc7, 0xfc, 0xd1, 0xc8, 0x9b, 0xc4, 0xd8, 0x9d, 0xc5, 0x91, 0x77, 0xc1, 0xc9, 0xa3,
	0xdb, 0x6e, 0xe1, 0xa5, 0x98, 0xeb, 0x06, 0x18, 0x76, 0x3b, 0x72, 0x51, 0xc8, 0x6e, 0x0a, 0x36,
	0x98, 0x30, 0x5e, 0x37, 0x16, 0x18, 0x55, 0x47, 0xee, 0x1c, 0xb9, 0x7f, 0x7a, 0xab, 0x85, 0x59,
	0xf8, 0x77, 0x5e, 0x9c, 0xaa, 0xa6, 0xff, 0x57, 0x59, 0x3e, 0x15, 0x57, 0x2a, 0x74, 0x60, 0x86,
	0xd0, 0xb5, 0x01, 0xfc, 0xbe, 0xce, 0xd4, 0x51, 0xd2, 0x68, 0xe5, 0xe4, 0x5d, 0x71, 0x6e, 0xd9,
	0x64, 0x59, 0xd7, 0xee, 0x3b, 0x93, 0x40, 0xb7, 0xa3, 0x8e, 0x91, 0x70, 0x1d, 0x94, 0x0f, 0xc5,
	0x25, 0x04, 0xf0, 0x67, 0xec, 0xce, 0x2a, 0x99, 0x51, 0xc7, 0x49, 0xb2, 0x49, 0xc8, 0x05, 0x71,
	0xb6, 0x02, 0x07, 0xe3, 0x11, 0xa8, 0x13, 0x24, 0x58, 0xc3, 0x70, 0x6d, 0x38, 0xee, 0xe9, 0x31,
	0xf8, 0xa5, 0x24, 0x71, 0x85, 0x0d, 0xdd, 0x8e, 0x9a, 0xe3, 0xb5, 0x35, 0x19, 0xf9, 0x5a, 0xcc,
	0x47, 0x8e, 0x7a, 0xe0, 0x8d, 0x4b, 0xfb, 0x41, 0xfb, 0xd0, 0xd1, 0x01, 0xd4, 0x49, 0xd2, 0x3b,
	0x44, 0x42, 0xbe, 0x12, 0xaa, 0xc1, 0xae, 0xda, 0x94, 0xb4, 0x4f, 0x91, 0xf6, 0x81, 0xbc, 0x7c,
	0x21, 0xae, 0x55, 0xbb, 0xfc, 0x77, 0xae, 0x77, 0x60, 0x1a, 0xef, 0x69, 0xd2, 0x3c, 0x80, 0xc5,
	0x7c, 0x54, 0x4c, 0xf5, 0x4f, 0xfb, 0x21, 0x38, 0x1f, 0x6d, 0x5c, 0xc3, 0xd7, 0x74, 0x8d, 0x67,
	0x5a, 0x7c, 0x4d, 0xd7, 0x17, 0xf9, 0x22, 0xa6, 0x5a, 0xdb, 0xd9, 0xba, 0xaf, 0x98, 0x93, 0x4f,
	0xc4, 0xe5, 0x0a, 0xef, 0x79, 0x97, 0x16, 0x49, 0x58, 0x71, 0x29, 0xa8, 0x73, 0xa4, 0xd2, 0x46,
	0x61, 0x1d, 0xd4, 0x2c, 0xd1, 0x72, 0xce, 0x73, 0x1d, 0x34, 0x88, 0x58, 0xfa, 0xdd, 0x08, 0xbc,
	0x0e, 0xc6, 0x59, 0x75, 0xa1, 0x2e, 0x3d, 0x21, 0x30, 0x43, 0x15, 0xb8, 0xb4, 0xaf, 0x4d, 0xa6,
	0xb7, 0x4d, 0x66, 0xc2, 0xf8, 0x1f, 0x67, 0x41, 0x5d, 0xe4, 0x0c, 0x1d, 0xc4, 0x63, 0x35, 0x55,
	0xdc, 0x16, 0xe4, 0xae, 0xf0, 0x54, 0xca, 0x97, 0xb8, 0x9a, 0x9a, 0x4c, 0xbc, 0x72, 0xce, 0xd9,
	0x10, 0x53, 0xa6, 0x64, 0x7d, 0xe5, 0x11, 0x25, 0xdf, 0x88, 0x1b, 0x15, 0xbc, 0xe9, 0xfc, 0x50,
	0x67, 0xe6, 0x33, 0x85, 0xbd, 0xa6, 0x93, 0xe0, 0xbc, 0xba, 0x4c, 0x9a, 0x87, 0x89, 0xc8, 0x8e,
	0xb8, 0x35, 0x4b, 0x43, 0x1a, 0x7b, 0xbf, 0x42, 0x36, 0x0e, 0x17, 0x8a, 0xf3, 0xbc, 0x52, 0x78,
	0x0f, 0x36, 0x19, 0x53, 0xd2, 0xae, 0xd6, 0xf3, 0x1c, 0x73, 0xf2, 0xb9, 0xb8, 0x3a, 0x59, 0x92,
	0xdd, 0xce, 0xc0, 0xa6, 0x90, 0x6e, 0x61, 0x71, 0x5c, 0x23, 0xa5, 0x76, 0xb2, 0x55, 0x6b, 0xc5,
	0xe5, 0x41, 0x5d, 0x3f, 0x40, 0x0b, 0xc9, 0x78, 0x67, 0x97, 0x23, 0x4f, 0xaa, 0xbe, 0xb3, 0x11,
	0xd5, 0xa2, 0x41, 0x5e, 0xbe, 0x68, 0xd5, 0x20, 0x1f, 0x51, 0x2e, 0xaa, 0xff, 0x0e, 0xe4, 0x89,
	0x37, 0x23, 0xaa, 0xb0, 0xf9, 0x7a, 0x2e, 0x5a, 0x44, 0xe4, 0x7d, 0x71, 0x61, 0x72, 0xea, 0xf4,
	0x27, 0xaa, 0xe2, 0x1b, 0xa4, 0x35, 0x0b, 0x63, 0xd6, 0xa2, 0x44, 0x58, 0x13, 0xf2, 0x1e, 0xf8,
	0x2d, 0xc8, 0xb1, 0x7b, 0x92, 0xb7, 0x9b, 0x9c, 0xb5, 0x43, 0x85, 0xe4, 0xb2, 0xb8, 0x39, 0x70,
	0x41, 0x67, 0x8c, 0x41, 0x3a, 0x23, 0xad, 0x6e, 0x91, 0x91, 0x43, 0x65, 0xb0, 0xc6, 0x6b, 0x3c,
	0x6b, 0xde, 0xe6, 0x1a, 0x6f, 0x32, 0xb8, 0xaf, 0x6d, 0xf1, 0x7e, 0xc9, 0xfb, 0xda, 0x16, 0xe5,
	0xa2, 0x90, 0xbd, 0x62, 0x3b, 0x33, 0xc9, 0x3b, 0xdb, 0x81, 0xa1, 0xb6, 0x9c, 0x88, 0x3b, 0xec,
	0xa1, 0xc9, 0x34, 0xe5, 0x29, 0xd5, 0x5f, 0xb5, 0xc9, 0x53, 0xa6, 0xa5, 0x38, 0x3e, 0x00, 0x3f,
	0x54, 0x0b, 0x24, 0x41, 0x63, 0xc4, 0x30, 0x14, 0xf5, 0x35, 0x63, 0x38, 0x96, 0x77, 0xc4, 0x99,
	0xb2, 0xe9, 0x6c, 0xea, 0x21, 0xa8, 0xbb, 0x44, 0xc5, 0x10, 0xde, 0x30, 0x71, 0x0f, 0x50, 0xdf,
	0xf0, 0x0d, 0x13, 0x63, 0xf2, 0xb6, 0x10, 0x2b, 0x99, 0x4b, 0xf6, 0xfa, 0x23, 0x80, 0x54, 0xdd,
	0x23, 0x89, 0x08, 0xc1, 0xee, 0xc4, 0xa7, 0x24, 0xbc, 0x05, 0x5b, 0x75, 0xa7, 0x6f, 0xb9, 0x3b,
	0x35, 0x08, 0xb4, 0xd6, 0x29, 0x7c, 0xe5, 0xef, 0x3e, 0x5b, 0x9b, 0x22, 0xf2, 0xa2, 0x38, 0xb6,
	0x9a, 0x14, 0xea, 0x3b, 0x22, 0x70, 0x88, 0x31, 0xae, 0x79, 0x37, 0x5c, 0x77, 0x09, 0x9b, 0x7e,
	0xc0, 0x31, 0xc6, 0x98, 0x7c, 0x20, 0x2e, 0xc6, 0x73, 0x2a, 0xc4, 0xef, 0x49, 0xae, 0x81, 0xcb,
	0x2b, 0xe2, 0xc4, 0x5b, 0xef, 0x8a, 0x91, 0x7a, 0x48, 0x02, 0x3c, 0x41, 0x0b, 0x34, 0x88, 0x0f,
	0xc0, 0x23, 0xb6, 0x30, 0x8b, 0xcb, 0x7b, 0xe2, 0x7c, 0xd7, 0xe6, 0x41, 0xdb, 0x04, 0xd6, 0xf4,
	0xd0, 0x64, 0x63, 0xb5, 0x48, 0x92, 0x33, 0x28, 0x46, 0x5e, 0x21, 0x14, 0xd1, 0x63, 0x8e, 0x3c,
	0xc6, 0xe8, 0x6d, 0x12, 0xcd, 0x4b, 0x7b, 0x4f, 0xca, 0xb7, 0x49, 0x83, 0x41, 0x9b, 0xeb, 0x26,
	0x01, 0x9b, 0xc3, 0x86, 0x4b, 0x21, 0x53, 0x3f, 0xb0, 0xcd, 0x18, 0x93, 0xf8, 0xf6, 0xa9, 0x76,
	0xeb, 0x29, 0xf1, 0x93, 0x39, 0xe9, 0xc7, 0xbb, 0xf4, 0xac, 0xd4, 0x8f, 0x77, 0xe8, 0xa5, 0xb8,
	0xbe, 0xa1, 0x3f, 0x75, 0xdd, 0x28, 0x5f, 0x2e, 0x7c, 0x1e, 0x7a, 0xe0, 0x3f, 0xe0, 0x19, 0xb2,
	0x09, 0xa8, 0xe7, 0x24, 0x7e, 0x10, 0x8d, 0xaf, 0xa0, 0x92, 0xda, 0x77, 0x59, 0x31, 0x04, 0xf5,
	0x23, 0xbf, 0x82, 0x6a, 0x20, 0x9e, 0xa8, 0x0d, 0xfd, 0x69, 0xb0, 0xeb, 0x5d, 0xb1, 0xb3, 0x3b,
	0x2a, 0x42, 0x29, 0xfb, 0x82, 0x4f, 0x54, 0x0b, 0x55, 0xda, 0x7d, 0x4f, 0x93, 0xbe, 0xf9, 0x0c,
	0xea, 0xa7, 0x89, 0xdd, 0x29, 0x28, 0xaf, 0x89, 0xb9, 0x0d, 0x18, 0x3a, 0x3f, 0x56, 0x2f, 0x89,
	0x2e, 0x67, 0xb8, 0xc7, 0x9b, 0x10, 0x3e, 0x3a, 0xbf, 0x17, 0x2f, 0xe5, 0x67, 0xde, 0xe3, 0x26,
	0x83, 0xeb, 0xaf, 0x5d, 0x3c, 0x68, 0xbc, 0xbc, 0x9f, 0x5e, 0xf1, 0xfa, 0x0f, 0xa0, 0xb1, 0x1f,
	0x96, 0x17, 0xb1, 0xdd, 0xe9, 0x8f, 0xf3, 0x00, 0x43, 0xf5, 0x0b, 0xf7, 0xc3, 0x19, 0x58, 0xde,
	0x14, 0xa7, 0xa7, 0x77, 0xf9, 0xaf, 0x24, 0x33, 0x05, 0xf0, 0x4c, 0xf5, 0x76, 0xc7, 0xb9, 0x49,
	0x74, 0xd6, 0xf3, 0x2e, 0x81, 0x3c, 0x77, 0x5e, 0xfd, 0xc6, 0x67, 0xaa, 0x41, 0x60, 0x3d, 0xf6,
	0x3c, 0x50, 0xb1, 0x64, 0x19, 0xa4, 0xfd, 0x8f, 0xea, 0x35, 0xd7, 0x63, 0x1d, 0xc5, 0x9b, 0x68,
	0xa2, 0xb4, 0xe4, 0x93, 0x5d, 0x13, 0x20, 0x09, 0x85, 0x07, 0xf5, 0x3b, 0xdf, 0x44, 0xad, 0x24,
	0xc5, 0x52, 0x11, 0x6b, 0xa0, 0x11, 0xcb, 0xd5, 0x9b, 0x32, 0x96, 0x59, 0x02, 0x33, 0x55, 0x36,
	0x98, 0xb2, 0x94, 0x97, 0x38, 0x53, 0x35, 0xb0, 0xec, 0x4c, 0xfb, 0x26, 0x37, 0xce, 0x42, 0xaa,
	0x96, 0x27, 0x9d, 0xa9, 0x82, 0x30, 0x97, 0x5b, 0xb0, 0x83, 0x9b, 0xb3, 0xc2, 0xb9, 0xe4, 0x19,
	0x6a, 0xf6, 0xc1, 0xef, 0x9b, 0x04, 0x12, 0xbc, 0xae, 0x3b, 0xac, 0x19, 0x41, 0x91, 0x84, 0xc5,
	0xae, 0xb7, 0x5a, 0x93, 0x40, 0x08, 0x7b, 0x4c, 0x7f, 0xaf, 0x50, 0x6b, 0xdc, 0x63, 0xfa, 0x7b,
	0x85, 0x54, 0xe2, 0x64, 0x3f, 0x38, 0xaf, 0x77, 0x40, 0xbd, 0x25, 0xb4, 0x9a, 0xe2, 0x79, 0x29,
	0x87, 0x2b, 0x99, 0xce, 0x73, 0xf5, 0x07, 0x9f, 0x97, 0x18, 0x8b, 0x64, 0x36, 0x20, 0x35, 0x5a,
	0x75, 0x6b, 0x32, 0x84, 0xa1, 0x87, 0x01, 0x58, 0x6d, 0x93, 0xb1, 0xfa, 0x93, 0x3d, 0x94, 0x53,
	0xec, 0x88, 0x03, 0x37, 0x39, 0xaf, 0x7f, 0x71, 0x47, 0x9c, 0x22, 0x98, 0xdd, 0xe9, 0x8c, 0xce,
	0xec, 0x3a, 0x67, 0xb7, 0x8e, 0x62, 0x14, 0x03, 0xaf, 0x6d, 0xfe, 0x01, 0x3c, 0x49, 0x6d, 0x70,
	0x14, 0x31, 0x86, 0x55, 0x47, 0x8f, 0xa0, 0x80, 0x02, 0x9b, 0x5c, 0x75, 0x13, 0x00, 0xef, 0x90,
	0xf7, 0xc9, 0xa8, 0x50, 0xef, 0xf8, 0x0e, 0xc1, 0x31, 0x46, 0xc7, 0x27, 0x8c, 0x6c, 0xf6, 0x38,
	0xba, 0x29, 0xf2, 0xf4, 0xb1, 0x38, 0xd9, 0xe3, 0xef, 0x36, 0x79, 0x17, 0x3f, 0xb9, 0xf2, 0x40,
	0x9f, 0x5c, 0x62, 0x71, 0xdb, 0x2d, 0xf2, 0xe7, 0xd4, 0xfc, 0x59, 0x1c, 0x57, 0xef, 0x81, 0xed,
	0x39, 0xfa, 0xbc, 0x7b, 0xf6, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xb7, 0x39, 0xce, 0xf3,
	0x0d, 0x00, 0x00,
}
